
psql << END
CREATE USER APP_TEST WITH PASSWORD \'${POSTGRES_TEST_PASSWORD}\';
CREATE USER APP_DEVELOPMENT WITH PASSWORD \'${POSTGRES_DEVELOPMENT_PASSWORD}\';
CREATE USER APP_PRODUCTION WITH PASSWORD \'${POSTGRES_PRODUCTION_PASSWORD}\';
CREATE DATABASE APP_TEST OWNER APP_TEST;
CREATE DATABASE APP_DEVELOPMENT OWNER APP_DEVELOPMENT;
CREATE DATABASE APP_PRODUCTION OWNER APP_PRODUCTION;
END